"""created parks table and seed

Revision ID: 3361901bfcd4
Revises: 3245644182c8
Create Date: 2023-04-05 09:28:53.382495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3361901bfcd4'
down_revision = '3245644182c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parks')
    # ### end Alembic commands ###
