"""added trail pic

Revision ID: b344299bcff0
Revises: 95e90cd8a3fd
Create Date: 2023-04-14 10:02:30.656790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b344299bcff0'
down_revision = '95e90cd8a3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
