"""added trails table

Revision ID: d9b34edb5022
Revises: 3361901bfcd4
Create Date: 2023-04-06 09:44:06.000837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b34edb5022'
down_revision = '3361901bfcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_trails_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trails')
    # ### end Alembic commands ###
